[[pages]]
path = "pages/eda.py"
name = "ĞŸÑ€ĞµĞ´Ğ¾Ğ±Ñ€Ğ°Ğ±Ğ¾Ñ‚ĞºĞ° Ğ´Ğ°Ğ½Ğ½Ñ‹Ñ…"
icon = "ğŸ“Š"

[[pages]]
path = "pages/author_info.py"
name = "Ğ˜Ğ½Ñ„Ğ¾Ñ€Ğ¼Ğ°Ñ†Ğ¸Ñ Ğ¾Ğ± Ğ°Ğ²Ñ‚Ğ¾Ñ€Ğµ"
icon = "ğŸ¤ "

[[pages]]
path = "pages/models.py"
name = "ĞœĞ¾Ğ´ĞµĞ»Ğ¸"
icon = "ğŸ’¡"

[[pages]]
path = "pages/about.py"
name = "Ğ ÑĞ°Ğ¹Ñ‚Ğµ"
icon = "â”"
